namespace EffectPerformanceAnalysis
{
    public enum EMetrics
    {
        [Display(Const.METRICS_NAME_SORTING_ORDER)]
        OrderInLayer,
        [Display(Const.METRICS_NAME_RENDER_QUEUE)]
        RenderQueue,
        [Display(Const.METRICS_NAME_MATERIAL_COUNT)]
        MaterialCount,
        [Display(Const.METRICS_NAME_PASS_COUNT)]
        PassCount,
        [Display(Const.METRICS_NAME_MESH_VERTEX_COUNT)]
        MeshVertexCount,
        [Display(Const.METRICS_NAME_MESH_VERTEX_ATTRIBUTES)]
        MeshVertexAttributes,
        [Display(Const.METRICS_NAME_MESH_TRIANGLE_COUNT)]
        MeshTriangleCount,
        [Display(Const.METRICS_NAME_RENDER_VERTEX_COUNT)]
        RenderVertexCount,
        [Display(Const.METRICS_NAME_RENDER_TRIANGLE_COUNT)]
        RenderTriangleCount,
        [Display(Const.METRICS_NAME_TEXTURE_COUNT)]
        TextureCount,
        [Display(Const.METRICS_NAME_TEXTURE_SIZE)]
        TextureSize,
        [Display(Const.METRICS_NAME_TEXTURE_MAX_WIDTH)]
        TextureMaxWidth,
        [Display(Const.METRICS_NAME_TEXTURE_MAX_HEIGHT)]
        TextureMaxHeight,
        [Display(Const.METRICS_NAME_TEXTURE_MEMORY)]
        TextureMemory,
        [Display(Const.METRICS_NAME_PARTICILE_MAX_COUNT)]
        ParticleMaxCount,
    }
}